import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    "polaris-web": "polaris-web.tsx",
    "AppProvider": "AppProvider.tsx",
    "Badge": "Badge.tsx",
    "Banner": "Banner.tsx",
    "BlockStack": "BlockStack.tsx",
    "Box": "Box.tsx",
    "Button": "Button.tsx",
    "ButtonGroup": "ButtonGroup.tsx",
    "Card": "Card.tsx",
    "Checkbox": "Checkbox.tsx",
    "ChoiceList": "ChoiceList.tsx",
    "ContextualSaveBar": "ContextualSaveBar.tsx",
    "Divider": "Divider.tsx",
    "DropZone": "DropZone.tsx",
    "EmptyState": "EmptyState.tsx",
    "FormLayout": "FormLayout.tsx",
    "Frame": "Frame.tsx",
    "Grid": "Grid.tsx",
    "HelpCard": "HelpCard.tsx",
    "Icon": "Icon.tsx",
    "IndexTable": "IndexTable.tsx",
    "InlineGrid": "InlineGrid.tsx",
    "InlineStack": "InlineStack.tsx",
    "Layout": "Layout.tsx",
    "Link": "Link.tsx",
    "List": "List.tsx",
    "MediaCard": "MediaCard.tsx",
    "Modal": "Modal.tsx",
    "Page": "Page.tsx",
    "ResourceItem": "ResourceItem.tsx",
    "ResourceList": "ResourceList.tsx",
    "Select": "Select.tsx",
    "Spinner": "Spinner.tsx",
    "Text": "Text.tsx",
    "TextField": "TextField.tsx",
    "Thumbnail": "Thumbnail.tsx",
    "Tooltip": "Tooltip.tsx",
    "icons/CheckCircleIcon": "icons/CheckCircleIcon.tsx",
  },
  format: ["esm", "cjs"],
  dts: true,
  sourcemap: true,
  clean: true,
  external: ["react", "react-dom", "react/jsx-runtime"],
  treeshake: true,
});
